-- Human-run only. Agent does not apply this against any database.
-- Schema: move category_intelligence off the junction; add listing template tables.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) category_intelligence (1:1 with category_marketplace)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category_intelligence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_marketplace_id BIGINT NOT NULL
        REFERENCES category_marketplace (id) ON DELETE CASCADE,
    intelligence JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT category_intelligence_category_marketplace_id_key
        UNIQUE (category_marketplace_id)
);

-- Backfill from the junction column (safe to re-run: skip existing FKs).
INSERT INTO category_intelligence (category_marketplace_id, intelligence)
SELECT cm.id, COALESCE(cm.category_intelligence, '{}'::jsonb)
FROM category_marketplace cm
WHERE NOT EXISTS (
    SELECT 1
    FROM category_intelligence ci
    WHERE ci.category_marketplace_id = cm.id
);

ALTER TABLE category_marketplace
    DROP COLUMN IF EXISTS category_intelligence;

-- ---------------------------------------------------------------------------
-- 2) listing_template (1:1 with category_marketplace)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS listing_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_marketplace_id BIGINT NOT NULL
        REFERENCES category_marketplace (id) ON DELETE CASCADE,
    gcs_object_key TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT listing_template_category_marketplace_id_key
        UNIQUE (category_marketplace_id)
);

-- ---------------------------------------------------------------------------
-- 3) listing_template_column (1:N)
-- Spine only: listing_template_id, column_index, display_order, config.
-- fill_type / requiredness / mappings / valid_values live in config JSONB only.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS listing_template_column (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_template_id BIGINT NOT NULL
        REFERENCES listing_template (id) ON DELETE CASCADE,
    column_index INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT listing_template_column_template_id_column_index_key
        UNIQUE (listing_template_id, column_index)
);

CREATE INDEX IF NOT EXISTS listing_template_column_template_id_display_order_idx
    ON listing_template_column (listing_template_id, display_order);

COMMIT;
